In [64]:
import numpy as np

In [13]:
b = np.array([[3,4,1],[45,3,21],[43,54,76],[45,87,1]])
b

array([[ 3,  4,  1],
       [45,  3, 21],
       [43, 54, 76],
       [45, 87,  1]])

In [14]:
#b here is a 2 dimensional array , you can quickly determine size of each dimension by looking at shape attribute of an array 
b.shape

(4, 3)

In [16]:
#if we want to extract value 54 from the array created above , we will need to access it with its indices across both the axes. 
b[2,1]

54

In [18]:
#slicing in arrays
#syntax array_name[rowstart:rowend:steps,columnstart:columnend:steps]
b[:2,1]

array([4, 3])

In [19]:
b[:,1]

array([ 4,  3, 54, 87])

In [23]:
#by default you can access all the elements of a single list in a 2d array by providing a single index as well
b[1]
b[2]

array([43, 54, 76])

In [24]:
b[[0,1,1],[1,2,1]]
#here elements will come from pairing of indices , (0,1) , (1,2) and (1,1)

array([ 4, 21,  3])

In [25]:
#you can use thin index access for modification as well
print(b)
b[[0,1,1],[1,2,1]]=[-10,-20,-30]
print(b)

[[ 3  4  1]
 [45  3 21]
 [43 54 76]
 [45 87  1]]
[[  3 -10   1]
 [ 45 -30 -20]
 [ 43  54  76]
 [ 45  87   1]]


In [26]:
# b>0 this will return boolean value as true and false on entire array
b>2

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True],
       [ True,  True, False]])

In [27]:
b[b>2]
#this will reurn the actual values in the arrays

array([ 3, 45, 43, 54, 76, 45, 87])

In [30]:
b

array([[  3, -10,   1],
       [ 45, -30, -20],
       [ 43,  54,  76],
       [ 45,  87,   1]])

In [38]:
b[:1,:2]

array([[  3, -10]])

In [40]:
b[2]>50

array([False,  True,  True])

In [67]:
#Generating random values
#used to genrate random numbers between 0 to 1
a=np.random.rand(20)
print(a)

[0.11182812 0.860995   0.59336978 0.24306295 0.56385032 0.37103429
 0.67900162 0.75356956 0.27495408 0.36428931 0.44974478 0.208523
 0.97500928 0.79732068 0.30202974 0.10660254 0.81749637 0.31998159
 0.98319106 0.98806468]


In [70]:
#randn fundtion: used to genarte random numbers which will follow normal distribution
b=np.random.randn(20)
print(b)

[ 1.38528039  0.23825765  0.35769547  1.7992677   0.71319393  1.1236914
  0.04444327 -1.0777365   1.74526182 -1.68221079 -1.41967776  0.92333665
 -1.60476134 -1.52059349  0.90872047  1.36203205 -2.40231787  0.50053034
  1.63214688  1.12008852]


In [77]:
#randint function: used to generate random integer number between two values
#It takes three parameters start point, end point and number of elements to be genrated (all in intergers)
c=np.random.randint(2,10,3)
c

array([9, 7, 8])

In [88]:
#We can also generate the arrays with random values
# you just have to pass size of the array
e=np.random.randint(-200,100,(4,6))
print(e)

[[  37   68   36    1   83   25]
 [ -39  -87   12 -158   74  -81]
 [ -10 -119  -65   89   65 -177]
 [  45  -42 -132 -168   46  -68]]


In [81]:
#arange function: similar to range function. Only difference is it can accept float values.
#It takes three parameters start point, end point and number of elements to be genrated
d=np.arange(2,10,5.3)
d

array([2. , 7.3])

In [85]:
#linspace: it is used to generate random numbers where you dont want to specify the steps and want system to calculate
#it takes three parameter start point, end point and number of elements to be ganerated
e=np.linspace(1,11,5)
print(e)

[ 1.   3.5  6.   8.5 11. ]


In [99]:
#choice function: If we want to select random values from an existing array
#It will be just picking values
f=np.random.randint(1,10,10)
print(f)
g=np.random.choice(f,6,False)
print(g)

[6 1 8 1 3 5 4 3 6 6]
[6 1 3 3 4 8]


In [101]:
h=np.random.choice(['a','b','c','f'],1000)
print(h)

['b' 'a' 'a' 'b' 'b' 'a' 'f' 'c' 'c' 'c' 'c' 'f' 'c' 'f' 'a' 'a' 'a' 'c'
 'c' 'b' 'f' 'f' 'f' 'f' 'a' 'b' 'b' 'c' 'c' 'c' 'f' 'b' 'b' 'b' 'b' 'f'
 'c' 'a' 'f' 'a' 'f' 'b' 'c' 'a' 'c' 'c' 'f' 'a' 'f' 'f' 'a' 'a' 'b' 'f'
 'c' 'b' 'a' 'c' 'f' 'c' 'f' 'b' 'c' 'a' 'a' 'c' 'f' 'c' 'c' 'f' 'c' 'b'
 'b' 'a' 'b' 'b' 'c' 'f' 'c' 'b' 'c' 'c' 'c' 'a' 'c' 'c' 'b' 'a' 'b' 'f'
 'b' 'f' 'a' 'c' 'f' 'b' 'c' 'a' 'f' 'b' 'c' 'b' 'b' 'f' 'f' 'a' 'f' 'b'
 'a' 'f' 'a' 'a' 'a' 'f' 'a' 'c' 'c' 'c' 'f' 'a' 'a' 'c' 'f' 'f' 'f' 'c'
 'b' 'b' 'f' 'a' 'a' 'f' 'a' 'c' 'f' 'f' 'f' 'c' 'c' 'f' 'a' 'b' 'f' 'f'
 'a' 'a' 'f' 'f' 'f' 'f' 'a' 'f' 'f' 'f' 'f' 'b' 'f' 'a' 'c' 'c' 'c' 'f'
 'b' 'b' 'f' 'c' 'f' 'f' 'b' 'b' 'c' 'c' 'b' 'c' 'a' 'f' 'a' 'a' 'a' 'a'
 'b' 'b' 'b' 'c' 'f' 'b' 'b' 'a' 'f' 'b' 'c' 'a' 'a' 'b' 'a' 'a' 'b' 'a'
 'f' 'b' 'f' 'c' 'c' 'b' 'b' 'c' 'b' 'b' 'b' 'b' 'b' 'f' 'b' 'a' 'a' 'b'
 'a' 'b' 'c' 'c' 'b' 'a' 'b' 'f' 'b' 'a' 'a' 'a' 'b' 'b' 'b' 'b' 'c' 'b'
 'c' 'b' 'a' 'f' 'b' 'a' 'f' 'c' 'f' 'a' 'c' 'c' 'f

In [105]:
#unique function
np.unique(h,return_counts=True)
#by default here all the variables get picked with almost equal probability in the random sample. 
#Although this doesnt mean that individual values are not random 
#but overall percentage of these variables remains almost same. 

(array(['a', 'b', 'c', 'f'], dtype='<U1'),
 array([240, 253, 256, 251], dtype=int64))

In [107]:
# We can force approx probability structure by using option p
i=np.random.choice(['a','b','c','f'],1000,p=[0.2,0.4,0.10,0.3])
print(i)

['b' 'f' 'f' 'f' 'b' 'a' 'f' 'f' 'b' 'b' 'a' 'b' 'b' 'f' 'b' 'a' 'f' 'b'
 'a' 'f' 'b' 'b' 'b' 'a' 'a' 'a' 'c' 'b' 'b' 'b' 'a' 'b' 'b' 'b' 'c' 'b'
 'b' 'b' 'f' 'f' 'b' 'a' 'b' 'f' 'f' 'f' 'b' 'f' 'a' 'a' 'a' 'f' 'b' 'a'
 'a' 'b' 'f' 'a' 'b' 'c' 'c' 'b' 'b' 'b' 'b' 'b' 'c' 'b' 'f' 'c' 'a' 'a'
 'a' 'b' 'b' 'b' 'b' 'b' 'c' 'f' 'a' 'f' 'b' 'f' 'b' 'a' 'b' 'f' 'b' 'f'
 'b' 'f' 'b' 'a' 'f' 'b' 'c' 'b' 'a' 'b' 'a' 'a' 'a' 'f' 'f' 'a' 'a' 'b'
 'a' 'c' 'f' 'c' 'a' 'b' 'b' 'b' 'f' 'f' 'b' 'c' 'a' 'a' 'f' 'b' 'f' 'b'
 'b' 'f' 'b' 'b' 'a' 'b' 'b' 'f' 'a' 'f' 'a' 'a' 'b' 'f' 'b' 'f' 'a' 'f'
 'b' 'b' 'b' 'b' 'b' 'a' 'f' 'a' 'f' 'f' 'b' 'b' 'f' 'b' 'b' 'b' 'a' 'b'
 'c' 'f' 'a' 'c' 'b' 'b' 'f' 'b' 'b' 'f' 'f' 'a' 'f' 'f' 'a' 'f' 'b' 'b'
 'b' 'b' 'b' 'b' 'b' 'b' 'f' 'f' 'f' 'a' 'a' 'a' 'a' 'f' 'a' 'b' 'a' 'b'
 'f' 'a' 'b' 'b' 'f' 'c' 'b' 'b' 'b' 'a' 'a' 'b' 'f' 'c' 'a' 'f' 'b' 'f'
 'f' 'b' 'f' 'b' 'b' 'c' 'a' 'c' 'f' 'c' 'a' 'b' 'f' 'f' 'b' 'a' 'f' 'b'
 'a' 'b' 'a' 'b' 'b' 'c' 'a' 'a' 'f' 'a' 'b' 'a' 'a

In [109]:
np.unique(i,return_counts=True)

(array(['a', 'b', 'c', 'f'], dtype='<U1'),
 array([215, 431,  87, 267], dtype=int64))

In [110]:
#sum function

my_array= np.array([[3,4,1],[45,3,21],[43,54,76],[45,87,1]])
print(my_array)

[[ 3  4  1]
 [45  3 21]
 [43 54 76]
 [45 87  1]]


In [111]:
# this simply sums the entire array
np.sum(my_array)

383

In [119]:
#Sum and other mathematical functions can work across dimensions or multiple values at once
#In that respect you can say axis=0 represent columns and axis=1 represent rows of an array
print(my_array)
np.sum(my_array,axis=1)
np.sum(my_array,axis=0)

[[ 3  4  1]
 [45  3 21]
 [43 54 76]
 [45 87  1]]


array([136, 148,  99])

In [121]:
#sqrt function: used to find the square root of elements in an array
np.sqrt(my_array)

array([[1.73205081, 2.        , 1.        ],
       [6.70820393, 1.73205081, 4.58257569],
       [6.55743852, 7.34846923, 8.71779789],
       [6.70820393, 9.32737905, 1.        ]])

In [122]:
np.sqrt(my_array[2])

array([6.55743852, 7.34846923, 8.71779789])

In [135]:
print(my_array)
np.min(my_array[1:3])

[[ 3  4  1]
 [45  3 21]
 [43 54 76]
 [45 87  1]]


3

In [138]:
np.max(my_array[0:2])

45

In [146]:
print(my_array)
np.mean(my_array[:2])

[[ 3  4  1]
 [45  3 21]
 [43 54 76]
 [45 87  1]]


12.833333333333334